import JSZip from "jszip";

/**
 * Bundle the generated code into a downloadable ZIP project.
 * Includes App.tsx, package.json, README, index.html, and entry point.
 */
export async function downloadProjectAsZip(
  code: string,
  promptText: string
): Promise<void> {
  const zip = new JSZip();

  // src/App.tsx
  zip.file("src/App.tsx", code);

  // src/index.tsx — entry point
  zip.file(
    "src/index.tsx",
    `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";

const root = ReactDOM.createRoot(
  document.getElementById("root") as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`
  );

  // src/index.css — Tailwind directives
  zip.file(
    "src/index.css",
    `@tailwind base;
@tailwind components;
@tailwind utilities;
`
  );

  // index.html
  zip.file(
    "index.html",
    `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mini Lovable App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/index.tsx"></script>
  </body>
</html>
`
  );

  // package.json
  zip.file(
    "package.json",
    JSON.stringify(
      {
        name: "mini-lovable-app",
        private: true,
        version: "1.0.0",
        type: "module",
        scripts: {
          dev: "vite",
          build: "vite build",
          preview: "vite preview",
        },
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0",
        },
        devDependencies: {
          "@types/react": "^18.2.0",
          "@types/react-dom": "^18.2.0",
          "@vitejs/plugin-react": "^4.0.0",
          autoprefixer: "^10.4.14",
          postcss: "^8.4.24",
          tailwindcss: "^3.3.0",
          typescript: "^5.0.0",
          vite: "^5.0.0",
        },
      },
      null,
      2
    )
  );

  // tailwind.config.js
  zip.file(
    "tailwind.config.js",
    `/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
`
  );

  // postcss.config.js
  zip.file(
    "postcss.config.js",
    `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`
  );

  // tsconfig.json
  zip.file(
    "tsconfig.json",
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          useDefineForClassFields: true,
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          module: "ESNext",
          skipLibCheck: true,
          moduleResolution: "bundler",
          allowImportingTsExtensions: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: "react-jsx",
          strict: true,
        },
        include: ["src"],
      },
      null,
      2
    )
  );

  // vite.config.ts
  zip.file(
    "vite.config.ts",
    `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
`
  );

  // README.md
  const sanitizedPrompt = promptText.replace(/`/g, "\\`");
  zip.file(
    "README.md",
    `# Mini Lovable — Generated App

This project was generated by [Mini Lovable](https://mini-lovable.vercel.app).

## Prompt Used

> ${sanitizedPrompt}

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:5173](http://localhost:5173) in your browser.

## Tech Stack

- React 18
- TypeScript
- Tailwind CSS
- Vite
`
  );

  // Generate and download
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "mini-lovable-project.zip";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
